name: "Build iOS IPA"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.MOBILEPROVISION_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Import Certificate (.p12)
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain

      - name: Flutter Build IPA
        run: |
          flutter pub get
          # 1. On crée l'archive SANS signature (pour éviter l'erreur de certificat dev)
          flutter build ipa --release --no-codesign
          
          # 2. On exporte l'IPA manuellement en utilisant ton certificat de distribution
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist \
            -allowProvisioningUpdates

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          # On cherche l'IPA, mais AUSSI le dossier .app au cas où
          path: |
            build/ios/ipa/*.ipa
            build/ios/iphoneos/*.app
          if-no-files-found: error